Fix/u potvrzeni nalezu samovysetreni kuze se zobrazuje spatny text#425
Loono-cz/loono pull request #426
Opened 2022-10-12 18:52 UTC by Brambora0

https://github.com/Loono-cz/loono-tasks/issues/100

2022-10-23 17:35 UTC, KeiShadow requested changes

2022-10-23 17:35 UTC, KeiShadow commented on lib/ui/screens/prevention/self_examination/has_finding_screen.dart
> +              text: 'www.mamo.cz',
Ten text do constants.

2022-10-23 17:35 UTC, KeiShadow commented on lib/ui/screens/prevention/self_examination/result_from_doctor.dart
> +    return '';
Tady misto return '' by mohl byt return by default:

2022-10-23 17:35 UTC, KeiShadow commented on lib/ui/screens/prevention/self_examination/result_from_doctor.dart
> +    return '';
tzn. ve switchi dám tag default a v něm vracím return '';

2022-10-23 17:35 UTC, KeiShadow commented on lib/ui/screens/prevention/self_examination/has_finding_screen.dart
>  }
Text je potřeba zformátovat.

2022-10-23 17:35 UTC, KeiShadow commented on lib/ui/screens/prevention/self_examination/result_from_doctor.dart
>  }
Text je potřeba zformátovat.

2022-10-23 18:08 UTC, Brambora0 commented on lib/ui/screens/prevention/self_examination/has_finding_screen.dart
>  }
@KeiShadow co přesně je potřeba zformátovat (nevidím na tom nic co by bylo potřeba)?

2022-10-24 11:12 UTC, KeiShadow commented on lib/ui/screens/prevention/self_examination/has_finding_screen.dart
>  }
Cely ten dokument, chybí formátování toho dokumentu, tak jak jsem se bavili, neprochází kvůli toho testy.

2022-10-24 11:27 UTC, merged