Fix/badge brzy vyprsi rozbita obrazovka#364
Loono-cz/loono pull request #436
Opened 2022-10-21 13:24 UTC by Brambora0

https://github.com/Loono-cz/loono-tasks/issues/6

2022-11-07 13:17 UTC, smolikjacgi requested changes
Prijde mi, ze vetev byla vytvorena z, do developu nezamergovane, vetve https://github.com/Loono-cz/loono/pull/433

proto tedy prvne prosim vyresit komentare tam a pote zde:))

2022-11-14 16:46 UTC, Brambora0 commented on lib/ui/widgets/examination_badge.dart
> +                  position: b.BadgePosition.bottomEnd(bottom: -8, end: -24),
neopakují se

2022-11-14 17:07 UTC, smolikjacgi commented on lib/ui/widgets/examination_badge.dart
> +                              .CUSTOM //TODO: customExamCount is probably only for first examination.
ta TODOcka jsou pouze pro tuto issue, nebo i do budoucna? Pokud jen pro tuto issue, tak prosim vyresit. Snazime se minimalizovat TODOcka:)

2022-11-15 18:50 UTC, Brambora0 commented on lib/ui/widgets/examination_badge.dart
> +                              .CUSTOM //TODO: customExamCount is probably only for first examination.
tohle tam bylo už před tímto problémem

2022-11-28 16:17 UTC, smolikjacgi approved these changes
lgtm(y)!

2022-11-28 16:24 UTC, smolikjacgi commented
Ahoj @Brambora0, prosim o vyreseni konfliktu. Dekuji!

2022-11-28 17:13 UTC, merged