Fix/pri zvetseni pisma apk nefunguje spravne#120
Loono-cz/loono pull request #449
Opened 2022-11-07 08:41 UTC by Brambora0

https://github.com/Loono-cz/loono-tasks/issues/120

2022-11-07 14:21 UTC, smolikjacgi requested changes
kukni prosim komenty

2022-11-07 14:21 UTC, smolikjacgi commented on lib/ui/widgets/onboarding/carousel/carousel_content.dart
> +                  style: const TextStyle(
napouziva se stejny textysle uz nekde? Neni v konstantach, nebo nestoji za to ho tam pridat?

2022-11-07 14:21 UTC, smolikjacgi commented on lib/ui/widgets/space.dart
> +class Space extends StatelessWidget {
Nebylo by lepsi neco jako CustomSpacer/LoonoSpacer,.. nebo neco co by davalo najevo, ze se jedna o nejakej custom spacer?:)

2022-11-07 20:25 UTC, Brambora0 commented on lib/helpers/size_helpers.dart
> +  bool get isMobileScreen => size.height <= 750;
750 bylo v LoonoSizes (ui_helpers.dart) a na android dokumentaci je to taky napsané
to `isScreenSmall` jsem tam dal hodnotu, abych vyzkoušel jaká je optimální, pak jsem zjistil, že to nepotřebuju a zapomněl to smazat
u `isTextBig` jsem to zkoušel

2022-11-14 17:00 UTC, smolikjacgi requested changes
prosim jeste barvicku do konstant

2022-11-14 17:43 UTC, smolikjacgi approved these changes
lgtm!(y)

2022-11-14 17:43 UTC, merged