Fix/v karte prohlidky lze upravit datum do budoucna#360
Loono-cz/loono pull request #454
Opened 2022-11-07 12:53 UTC by Brambora0

2022-11-07 14:25 UTC, smolikjacgi requested changes
prosim koukni na datepicker a zda v aplikaci potrebujeme 2 ruzne

2022-11-07 14:25 UTC, smolikjacgi commented on lib/ui/widgets/prevention/date_picker.dart
> +class DatePicker extends StatefulWidget {
prosim o prejmenovani, z nazvu nelze poznat o najky datepicker se jedna. btw potrebujeme 2 custom datepickery?

2022-11-28 16:21 UTC, smolikjacgi approved these changes
lgtm(y)

2022-12-14 08:51 UTC, smolikjacgi commented
@Brambora0 potreba otestovat, melo by byt osetreno ve stavajici verzi. Novy datepicker by byl tedy zbytecny.

2022-12-19 12:29 UTC, Brambora0 commented
Jo už je vyřešeno

2022-12-19 12:29 UTC, closed without merging