Routing push notifikaci#460
Loono-cz/loono pull request #466
Opened 2022-12-06 20:08 UTC by Brambora0

https://github.com/Loono-cz/loono/issues/460 + https://github.com/Loono-cz/loono-tasks/issues/30

2022-12-19 16:46 UTC, smolikjacgi requested changes
prosim viz komenty

2022-12-19 16:46 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +    log('open push notification on $categorized');
chceme nechavat log?

2022-12-19 16:46 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +      log('examination with uuid $uuid was not found');
chceme nechavat log?

2022-12-19 16:46 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +          log('Unable to fetch examination data for notifications');
chceme logovat?

2022-12-19 16:46 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +      var sex = Sex.MALE;
proc defaultne muz a neni optional, kdyz muze byt null?

2022-12-19 16:46 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +      log('self examination with uuid $uuid was not found');
logovani

2022-12-19 16:46 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +          log('Unable to fetch examination data for notifications');
chceme logovat?

2022-12-19 16:46 UTC, smolikjacgi commented on lib/ui/screens/main/main_screen.dart
> +  final NotificationRouter? notificationRouter;
potrebujeme instanci, nebo lze router pojmout jako singleton? Jen otazka, zda NotificationRouter musi doopravny nest nejaka data.

2022-12-19 17:05 UTC, Brambora0 commented on lib/ui/screens/main/main_screen.dart
> +  final NotificationRouter? notificationRouter;
Používá se 1 instance uložená v registry

2022-12-19 17:12 UTC, smolikjacgi commented on lib/ui/screens/main/main_screen.dart
> +  final NotificationRouter? notificationRouter;
je instance potreba? Potrebuje NotficationRouter lokalni promenne?

2022-12-19 17:18 UTC, Brambora0 commented on lib/ui/screens/main/main_screen.dart
> +  final NotificationRouter? notificationRouter;
Nemusí to být lokální proměnná (nevím proč jsem to tak udělal), nahradil jsem to getrem z registry `AppRouter get appRouter => registry.get<AppRouter>();`

2022-12-21 07:07 UTC, smolikjacgi requested changes
prosim jeste malickost viz komenty, presunout konstanty do filu s konstantama aby byly na jednom miste. Trida LoonoStrings

2022-12-21 07:07 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +  static const screenParamName = 'screen';
prosim presunout nekam do filu s konstantama

2022-12-21 07:07 UTC, smolikjacgi commented on lib/router/notification_router.dart
> +  static const uuidParamName = 'examinationUuid';
prosim presunout nekam do filu s konstantama

2022-12-21 07:16 UTC, smolikjacgi commented on lib/ui/screens/main/main_screen.dart
> +  final NotificationRouter? notificationRouter;
supr!

2022-12-21 16:57 UTC, smolikjacgi approved these changes
lgtm!

2023-01-02 10:15 UTC, merged