fix #19: Hide/show selected/unselected clusters
Loono-cz/loono pull request #474
Opened 2022-12-21 12:52 UTC by magdalenamajakova

Po kliknutí na cluster ostatné zmiznú z mapy, stanú sa neaktívnymi. Po opatovnom kliknutí (deselect) sa opat objavia na mape všetky aktuálne dostupné clustery.

https://github.com/Loono-cz/loono-tasks/issues/19

2022-12-28 17:37 UTC, smolikjacgi requested changes
Ahoj, prosim o upravu viz komenty:)

2022-12-28 17:37 UTC, smolikjacgi commented on lib/services/map_state_sevice.dart
> +  bool isAnyMarkerSelected = false;
Pokud se jedna o private promennou, prosim _ pred nazev

2022-12-28 17:57 UTC, magdalenamajakova reviewed
reviewed

2022-12-28 19:05 UTC, smolikjacgi approved these changes
lgtm!

2022-12-29 10:32 UTC, aaackoo approved these changes

2023-01-02 10:35 UTC, merged