Feat/fe formular dotaz do odborne poradny#467
Loono-cz/loono pull request #476
Opened 2022-12-29 10:26 UTC by adamsupej

Bol implementovany formular so vsetkymi pozadovanymi funkciami, okrem odoslania vysledku na email.

#467

2022-12-29 13:54 UTC, smolikjacgi requested changes
Ahoj, pisnul jsem par komentaru, prosim o upravu a pak like nebo reakci na koment:) Jinak lgtm!

2022-12-29 13:54 UTC, smolikjacgi commented on lib/ui/widgets/form/form_content.dart
> +enum QuestionTypes {
Prosim o prejmenovani enumu na 'FormQuestionType'. Kdyz se enum tranzitivnim importovanim dostane nekam, kde nebude na prvni pohled davat smysl, prefix Form pomuze rozlisit (treba kdyz jsou v app jine questions nez z formu). Jednotne cislo se pro nazev ciselniku hodi lepe, kdyz pristupujeme k jednotlivym casum

2022-12-29 13:54 UTC, smolikjacgi commented on lib/ui/widgets/form/form_content.dart
> +  final QuestionTypes _questionType;
zde prosim bez _ 

neni to uplne lokalni promenna, kdyz ji volas pres teckovou anotaci z _FormContentState. Divim se, ze to nekrici :D

2022-12-29 22:53 UTC, adamsupej commented
Upravene :)

2023-01-02 10:23 UTC, smolikjacgi approved these changes

2023-01-02 10:33 UTC, smolikjacgi requested changes
jeste jsem hodil komenty na force unwrap. Prosim koukni na ne:)

2023-01-02 10:33 UTC, smolikjacgi commented on lib/ui/widgets/form/form_content.dart
> +  final _currentUser = registry.get<DatabaseService>().users.user!;
jeste prosim odebrat '!'. Neni bezpecne

2023-01-02 10:33 UTC, smolikjacgi commented on lib/ui/widgets/form/form_content.dart
> +                    context.l10n.form_question_answer('"${_currentUser.email!}"'),
prosim odebrat '!'. Neni bezpecne

2023-01-03 14:48 UTC, adamsupej commented
Opravene :)

2023-01-03 16:38 UTC, smolikjacgi approved these changes
lgtm!

2023-01-03 17:20 UTC, merged