Fix/nezobrazuje se spravne splash screen#68
Loono-cz/loono pull request #487
Opened 2023-01-18 18:23 UTC by Brambora0

https://github.com/Loono-cz/loono-tasks/issues/68
Kvůli změně systému splash screen od Androidu 12 - jsou k dispozici příliš malé plochy pro hlavní ikonu a spozory. Se splash screen musí zobrazit po načtení aplikace jako normální obrazovka v aplikaci.

2023-01-23 08:17 UTC, smolikjacgi commented
Ahoj, znamena to tedu, ze pokud je obrazovka mensi nez nejaky rozmer, tak se od Androidu 12 nezobrazi zadna splashscreena, ale jen bila/cerna obrazovka? Zobrazuje se splashscreena na vetsich devicech dle designu (jako na iOS) se sponzorama?

2023-01-23 08:40 UTC, Brambora0 commented
Ne problém je že na Android 12+ je omezený prostor pro zobrazení log, takže by to bylo moc malé (bílé prostory na obrázku). Na starších Androidech a na IOS by mělo být v pořádku.

![image](https://user-images.githubusercontent.com/58693944/213996735-a6fbda0a-aaf9-4b46-8da9-0af40ec3db57.png)
![image (1)](https://user-images.githubusercontent.com/58693944/213996740-f2c2dbf8-f798-4b79-9393-bc8559996c26.png)

2023-01-25 09:16 UTC, KarelSima commented
Ahoj všem :) 
z vlastní zkušenosti pokud na splashscreen není jen ikona aplikace nebo logo, max s nějakým backgroundem.
Tak dává smysl mít vlastní screenu, která se načte jako první a poté se začnou loadovat data přes state do aplikace :) 
Třeba s LoadingWeel, aby uživatel věděl že se něco děje :) 

Dá se pak splash screen také dobře upravovat, navrhnout/rozvrhnout a případně použít i responzivní framework, který
umí pomoct aby splash screana vypadala téměř shodně na všech zařízeních :) a byly obrázky například čitelné apod.
Samozřejmě je pak super mít obrázky a loga ve vektorové grafice :) aby si to vykreslovací vrstva přepočítala sama :) 

Co se týká té responsivity, tak já mám dobré zkušenosti z projektu z loňského roku s tímto :)
https://pub.dev/packages/responsive_framework

2023-01-25 09:36 UTC, Brambora0 commented
Ahoj, @KarelSima chápu to správně, že by bylo dobré, aby na systémové splashscreen bylo jen logo a pak hned se zobrazila screen v aplikaci (jako splashscreen).
Pokud ano, tak tohle přesně dělám u Androidu 12+ i s svg logy (protože se to na systémovou ani nevejde), nebyl by problém tak udělat u všech, ale by bylo asi potřeba domluvit s UX.

2023-01-25 10:02 UTC, KarelSima commented
@KarelSima v jednom mém předchozím projektu zákazník měl, specifické požadavky :) a chtěl splashscreen, takže jsme šli touto cestou, fungovalo nám to na andorid tabletech iOS tabletech i na Flutter Web buildu nasazeném :) 
A asi to bylo za mě nejlepší řešení :) jednotné napříč vším :)

2023-02-08 08:21 UTC, KarelSima approved these changes
lgtm!

2023-02-16 18:43 UTC, smolikjacgi requested changes
mensi upravy prosim

zkousel jsi, jestli splashscreena funguje spravne kdyz otevres app napr v rozdelanem onboardingu? Neni nejaky case, kdy to fungovat nemuze? (je to otestovane?)

Mergni si prosim aktualni develop do vetve, pokud tak nemas

2023-02-16 18:43 UTC, smolikjacgi commented on lib/loono.dart
> +            log(appRouter.currentPath.toString());
potrebujeme/chceme log? Neni to pozustatek z debugu?

2023-02-16 18:43 UTC, smolikjacgi commented on lib/loono.dart
> +            _showMainScreen(appRouter, delay: const Duration(seconds: 5));
proc mame pevny delay? Nechceme pouze cekat na nacteni appky, ktere by melo byt co nejrychlejsi?

2023-02-16 18:47 UTC, Brambora0 commented on lib/loono.dart
> +            _showMainScreen(appRouter, delay: const Duration(seconds: 5));
Jestli se má zobrazovat splashscreen z komponent, tak ta se může zobrazit až po načtení aplikace. Těch 5s jsem tam dal aby se to dalo přečíst.

2023-02-16 18:48 UTC, Brambora0 commented on lib/loono.dart
> +            log(appRouter.currentPath.toString());
Je :) odstraním

2023-02-16 18:51 UTC, smolikjacgi commented on lib/loono.dart
> +            _showMainScreen(appRouter, delay: const Duration(seconds: 5));
kdyz se app nacita, co je na realne systemove splashscreene a jak dlouho? Tyka se ios a Andoidu stejne?

2023-02-17 08:45 UTC, smolikjacgi approved these changes
lgtm!

2023-02-17 08:49 UTC, adamsupej approved these changes
lgtm

2023-02-17 13:19 UTC, merged