Fix/routing push notifikaci
Loono-cz/loono pull request #516
Opened 2023-02-01 12:32 UTC by Brambora0

Zobrazení načítací obrazovky notifikace jako app screen - zabránění zobrazení šedé obrazovky.

2023-02-08 08:23 UTC, KarelSima approved these changes
lgtm!

2023-02-16 18:24 UTC, smolikjacgi requested changes
prosim drobnou upravu

2023-02-16 18:24 UTC, smolikjacgi commented on lib/router/app_router.dart
> +    AutoRoute<void>(
prosim definovat route do lokalni promenne viz vyse

2023-02-16 18:44 UTC, smolikjacgi approved these changes
lgtm! (y)

2023-02-16 18:44 UTC, merged