Fix/tod os fix#158
Loono-cz/loono pull request #522
Opened 2023-02-24 16:59 UTC by adamsupej

Boli implementované a opravené viaceré tasky, z toho najdôležitejšie nasledovné:
- odstránené neaktuálne TODO,
- opravené linty,
- opravené null warning,
- extractovanie stringov do l10n,
- pridané bezpečné generovanie klúča na prístup k databáze a uloženie do secure storage,
- upravený odhlasovací flow,
- extractovaný navigation builder z PreAuth a MainScreen do separátneho widgetu,
- vyťahovanie kontaktých informácii z doctorSearch,
- odstránenie customExam z kalendáru.

2023-02-24 17:39 UTC, Brambora0 requested changes

2023-02-24 17:39 UTC, Brambora0 commented on lib/ui/widgets/bottom_navigation_builder.dart
> +        iconPath: 'assets/icons/tabs/explore.svg',
Tohle by asi mělo být v constants.dart

2023-02-24 17:40 UTC, Brambora0 commented on lib/ui/screens/logout.dart
> -    appClear().then((value) {
Prosím nech tam `registry.get<NotificationService>().enableNotifications(false);`. Řešení chození notifikací odhlášeným uživatelům https://github.com/Loono-cz/loono-tasks/issues/132.

2023-02-24 20:33 UTC, adamsupej commented on lib/ui/screens/logout.dart
> -    appClear().then((value) {
To som neodstranoval, to by tam malo byt zanechane

2023-02-25 07:25 UTC, Brambora0 commented on lib/ui/screens/logout.dart
> -    appClear().then((value) {
Asi jsi to odstranil omylem - pouzity to neni 
![image](https://user-images.githubusercontent.com/58693944/221344671-114cb36f-55cc-4e23-ac7a-50b7f150afb2.png)

2023-02-25 09:45 UTC, adamsupej commented on lib/ui/screens/logout.dart
> -    appClear().then((value) {
Ja som to prehodil do openSettings, tam išlo o to, že ak počas logoutu dojde k chybe tak initState nedobehne spravne, ale stále dojde k routingu na logoutScreen, preto som to prehodil do openSettings a ak všetko dopadne OK, tak nastane routing.

2023-02-25 13:24 UTC, Brambora0 commented on lib/ui/screens/logout.dart
> -    appClear().then((value) {
Aha,promiň jsem si to nespojil

2023-02-27 09:35 UTC, smolikja requested changes
supr prace! Koukni prosim jeste na drobnejsi komenty)

2023-02-27 09:35 UTC, smolikja commented on integration_test/test_sets/onboarding/test_cases/other/loon_542_installing_and_opening_app.dart
>    // await introVideoPage.replayVideo();
proc tu zustava tento comment? Ma to neco spolecneho s vymazanym TODO?

2023-02-27 09:35 UTC, smolikja commented on integration_test/test_sets/settings/test_cases/delete_account/loon_465_delete_account_and_contact_straight_path.dart
>    // await afterDeletionPage.clickSendEmailButton();
souvisi zakomentovany s vymazanym TODOckem?

2023-02-27 09:35 UTC, smolikja commented on lib/services/secure_storage_service.dart
> +    for (var i = 0; i < 20; i++) {
prosim ted 20 do lokalni konstanty ve fci, jen aby bylo jasne proc tech 20. treba 'passwordLeght'

2023-02-27 09:35 UTC, smolikja commented on lib/ui/widgets/bottom_navigation_builder.dart
> +        iconPath: 'assets/icons/tabs/explore.svg',
(y) ikonky prosim do konstant:)

2023-02-27 09:35 UTC, smolikja commented on lib/ui/widgets/find_doctor/search_doctor_card.dart
> +                                      'assets/icons/telephone.svg',
prosim do konstant

2023-02-27 09:35 UTC, smolikja commented on lib/ui/widgets/find_doctor/search_doctor_card.dart
> +                                      'assets/icons/at.svg',
prosim do konstant

2023-02-27 09:35 UTC, smolikja commented on lib/ui/widgets/prevention/last_visit_sheet.dart
> +    // TODO: replace now() with date of Account creation
supr

2023-02-27 09:50 UTC, adamsupej commented on integration_test/test_sets/onboarding/test_cases/other/loon_542_installing_and_opening_app.dart
>    // await introVideoPage.replayVideo();
Toto je sucast integration testov, ktore sa neriesili.

2023-02-27 09:50 UTC, adamsupej commented on integration_test/test_sets/settings/test_cases/delete_account/loon_465_delete_account_and_contact_straight_path.dart
>    // await afterDeletionPage.clickSendEmailButton();
Toto je sucast integration testov, ktore sa neriesili.

2023-02-27 09:51 UTC, adamsupej commented on lib/ui/screens/logout.dart
> -    appClear().then((value) {
Prepac, ja som to mohol napisat do info.

2023-02-27 10:10 UTC, smolikja approved these changes
lgtm!

2023-02-27 10:32 UTC, Brambora0 approved these changes

2023-02-27 10:39 UTC, merged