Feat/odber newsletteru existujici uzivatel#109
Loono-cz/loono pull request #524
Opened 2023-02-24 20:49 UTC by magdalenamajakova

2023-02-27 09:20 UTC, smolikja requested changes
Super prace!:) Jeste jsem hodil par komentu a drobne upravy. Vyres prosim analyze a hod ke komentum like az budou za tebe ok

2023-02-27 09:20 UTC, smolikja commented on lib/ui/screens/notification_page.dart
> +  Future<void> donationFunction() async {
pokud se jedna pouze o lokalni fci, prosim nazev s prefixem '_' -> '_donationFunction'

2023-02-27 09:20 UTC, smolikja commented on lib/ui/screens/notification_page.dart
> +  Future<void> newsletterButtonFunction() async {
pokud je fce lokalni, prosim opet prefix _

2023-02-27 09:20 UTC, smolikja commented on lib/ui/screens/notification_page.dart
> +            SvgPicture.asset('assets/donate_ilustration.svg')
cestu k assetu do konstant prosim

2023-02-27 09:20 UTC, smolikja commented on lib/ui/screens/notification_page.dart
> +            SvgPicture.asset('assets/newsletter_illustration.svg'),
cestu k assetu do konstant prosim

2023-02-27 09:20 UTC, smolikja commented on lib/utils/newsletter_utils.dart
> +  final dateNewOnBoarding = DateTime.utc(2022, 10, 11);
prosim bez toho 'utc', aby byl cas lokalni

2023-02-27 09:20 UTC, smolikja commented on lib/utils/newsletter_utils.dart
> +  bool mounted = true,
mounted nemuzes napevno nastavovat na true, musi se propsat z parentu (mounted u ale stejne cekujes vys). Odstran prosim celou fci, provolani 2 radku muze byt porimo, vyse jak fci volas:)

2023-02-27 09:20 UTC, smolikja commented on lib/utils/newsletter_utils.dart
> +      Future.delayed(
jen pro kontrolu, je to jedine misto, ze ktereho se delay pro notif vola?:) Prosim jeste cas delay hodit do konstant

2023-02-27 09:20 UTC, smolikja commented on lib/utils/newsletter_utils.dart
> +///Function to show newsletter page
docs super!:)

2023-02-27 09:20 UTC, smolikja commented on lib/models/user.dart
> +  BoolColumn get newsletterNotificationShown =>
dobra prace

2023-02-27 16:32 UTC, smolikja approved these changes
lgtm!

2023-02-28 19:38 UTC, Brambora0 approved these changes

2023-03-01 08:30 UTC, adamsupej approved these changes
Lgtm

2023-03-03 18:44 UTC, smolikjacgi approved these changes

2023-03-03 18:50 UTC, merged